version: '3.8'

services:
  # Node.js Backend Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - PORT=3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: website_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Adminer (Database Management Interface)
  adminer:
    image: adminer
    container_name: website_adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
